using Application.Features.Contracts.Milestones.Common.DTOs;
using Application.Features.Contracts.Milestones.WorkItems.Common.DTOs;
using MediatR;

namespace Application.Features.Contracts.Milestones.WorkItems.Freelancer.Submit.Commands;

/// <param name="SubmissionBatchId">
/// Generated by the browser when the freelancer presses "submit selected". Used as the idempotency
/// key so a retried request cannot create a second revision, and to correlate one email per batch
/// rather than one per work item.
/// </param>
public sealed record SubmitContractWorkItemsCommand(
    Guid ContractId,
    Guid MilestoneId,
    Guid UserId,
    Guid SubmissionBatchId,
    IReadOnlyList<SubmitWorkItemEntry> Items) : IRequest<ContractMilestoneResponse>;
