using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ConvertFaqIdsToInt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "FAQs" DROP CONSTRAINT IF EXISTS "FAQs_faqCat_FAQCategoriesId_fkey";
                DROP INDEX IF EXISTS "IX_FAQs_FAQCategoriesId";
                ALTER TABLE "FAQs" DROP CONSTRAINT IF EXISTS "FAQs_pkey";
                ALTER TABLE "FAQCategories" DROP CONSTRAINT IF EXISTS "FAQCategories_pkey";

                ALTER TABLE "FAQCategories" ADD COLUMN "FAQCategoriesId_int" integer;
                ALTER TABLE "FAQs" ADD COLUMN "FAQsId_int" integer;
                ALTER TABLE "FAQs" ADD COLUMN "FAQCategoriesId_int" integer;

                WITH numbered_categories AS (
                    SELECT
                        ctid,
                        ROW_NUMBER() OVER (
                            ORDER BY "SortOrder" NULLS LAST, "Slug", "FAQCategoriesId"::text
                        )::integer AS new_id
                    FROM "FAQCategories"
                )
                UPDATE "FAQCategories" category
                SET "FAQCategoriesId_int" = numbered_categories.new_id
                FROM numbered_categories
                WHERE category.ctid = numbered_categories.ctid;

                WITH numbered_faqs AS (
                    SELECT
                        ctid,
                        ROW_NUMBER() OVER (
                            ORDER BY "SortOrder" NULLS LAST, "CreatedAt", "FAQsId"::text
                        )::integer AS new_id
                    FROM "FAQs"
                )
                UPDATE "FAQs" faq
                SET "FAQsId_int" = numbered_faqs.new_id
                FROM numbered_faqs
                WHERE faq.ctid = numbered_faqs.ctid;

                UPDATE "FAQs" faq
                SET "FAQCategoriesId_int" = category."FAQCategoriesId_int"
                FROM "FAQCategories" category
                WHERE faq."FAQCategoriesId" = category."FAQCategoriesId";

                ALTER TABLE "FAQCategories" ALTER COLUMN "FAQCategoriesId_int" SET NOT NULL;
                ALTER TABLE "FAQs" ALTER COLUMN "FAQsId_int" SET NOT NULL;
                ALTER TABLE "FAQs" ALTER COLUMN "FAQCategoriesId_int" SET NOT NULL;

                ALTER TABLE "FAQs" DROP COLUMN "FAQCategoriesId";
                ALTER TABLE "FAQs" DROP COLUMN "FAQsId";
                ALTER TABLE "FAQCategories" DROP COLUMN "FAQCategoriesId";

                ALTER TABLE "FAQCategories" RENAME COLUMN "FAQCategoriesId_int" TO "FAQCategoriesId";
                ALTER TABLE "FAQs" RENAME COLUMN "FAQsId_int" TO "FAQsId";
                ALTER TABLE "FAQs" RENAME COLUMN "FAQCategoriesId_int" TO "FAQCategoriesId";

                ALTER TABLE "FAQCategories" ALTER COLUMN "FAQCategoriesId" ADD GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE "FAQs" ALTER COLUMN "FAQsId" ADD GENERATED BY DEFAULT AS IDENTITY;

                SELECT setval(
                    pg_get_serial_sequence('"FAQCategories"', 'FAQCategoriesId'),
                    GREATEST(COALESCE((SELECT MAX("FAQCategoriesId") FROM "FAQCategories"), 0), 1),
                    true
                );

                SELECT setval(
                    pg_get_serial_sequence('"FAQs"', 'FAQsId'),
                    GREATEST(COALESCE((SELECT MAX("FAQsId") FROM "FAQs"), 0), 1),
                    true
                );

                ALTER TABLE "FAQCategories" ADD CONSTRAINT "FAQCategories_pkey" PRIMARY KEY ("FAQCategoriesId");
                ALTER TABLE "FAQs" ADD CONSTRAINT "FAQs_pkey" PRIMARY KEY ("FAQsId");
                CREATE INDEX "IX_FAQs_FAQCategoriesId" ON "FAQs" ("FAQCategoriesId");
                ALTER TABLE "FAQs"
                    ADD CONSTRAINT "FAQs_faqCat_FAQCategoriesId_fkey"
                    FOREIGN KEY ("FAQCategoriesId")
                    REFERENCES "FAQCategories" ("FAQCategoriesId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "FAQs" DROP CONSTRAINT IF EXISTS "FAQs_faqCat_FAQCategoriesId_fkey";
                DROP INDEX IF EXISTS "IX_FAQs_FAQCategoriesId";
                ALTER TABLE "FAQs" DROP CONSTRAINT IF EXISTS "FAQs_pkey";
                ALTER TABLE "FAQCategories" DROP CONSTRAINT IF EXISTS "FAQCategories_pkey";

                ALTER TABLE "FAQCategories" ADD COLUMN "FAQCategoriesId_uuid" uuid;
                ALTER TABLE "FAQs" ADD COLUMN "FAQsId_uuid" uuid;
                ALTER TABLE "FAQs" ADD COLUMN "FAQCategoriesId_uuid" uuid;

                UPDATE "FAQCategories"
                SET "FAQCategoriesId_uuid" = gen_random_uuid();

                UPDATE "FAQs"
                SET "FAQsId_uuid" = gen_random_uuid();

                UPDATE "FAQs" faq
                SET "FAQCategoriesId_uuid" = category."FAQCategoriesId_uuid"
                FROM "FAQCategories" category
                WHERE faq."FAQCategoriesId" = category."FAQCategoriesId";

                ALTER TABLE "FAQCategories" ALTER COLUMN "FAQCategoriesId_uuid" SET NOT NULL;
                ALTER TABLE "FAQs" ALTER COLUMN "FAQsId_uuid" SET NOT NULL;
                ALTER TABLE "FAQs" ALTER COLUMN "FAQCategoriesId_uuid" SET NOT NULL;

                ALTER TABLE "FAQs" DROP COLUMN "FAQCategoriesId";
                ALTER TABLE "FAQs" DROP COLUMN "FAQsId";
                ALTER TABLE "FAQCategories" DROP COLUMN "FAQCategoriesId";

                ALTER TABLE "FAQCategories" RENAME COLUMN "FAQCategoriesId_uuid" TO "FAQCategoriesId";
                ALTER TABLE "FAQs" RENAME COLUMN "FAQsId_uuid" TO "FAQsId";
                ALTER TABLE "FAQs" RENAME COLUMN "FAQCategoriesId_uuid" TO "FAQCategoriesId";

                ALTER TABLE "FAQCategories" ALTER COLUMN "FAQCategoriesId" SET DEFAULT gen_random_uuid();
                ALTER TABLE "FAQs" ALTER COLUMN "FAQsId" SET DEFAULT gen_random_uuid();

                ALTER TABLE "FAQCategories" ADD CONSTRAINT "FAQCategories_pkey" PRIMARY KEY ("FAQCategoriesId");
                ALTER TABLE "FAQs" ADD CONSTRAINT "FAQs_pkey" PRIMARY KEY ("FAQsId");
                CREATE INDEX "IX_FAQs_FAQCategoriesId" ON "FAQs" ("FAQCategoriesId");
                ALTER TABLE "FAQs"
                    ADD CONSTRAINT "FAQs_faqCat_FAQCategoriesId_fkey"
                    FOREIGN KEY ("FAQCategoriesId")
                    REFERENCES "FAQCategories" ("FAQCategoriesId");
                """);
        }
    }
}
